# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Tampa Bay Book Group
tagline:          'A book group'
description:      '' 

# Custom vars
gems: ['jekyll-paginate', 'jekyll-amazon']

timezone: America/New_York
amazon_locale : en

# Prod vs. Dev
destination:      ../ort-prod/ort/
url:              http://tampabaybookgroup.org
baseurl:          /
