# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Tampa Bay Book Group
tagline:          'A book group'
description:      '' 

# Custom vars
gems: ['jekyll-paginate', 'jekyll-amazon']

timezone: America/New_York
amazon_locale : en

# Prod vs. Dev
url:              http://localhost:8888/ort/_site 
baseurl:          /ort/_site/
